### ISSUE TITLE
Messages buffered not yet written out - what happens to them when system is terminated

### ISSUE THREAD

**Issue by dimanyudev** [cloudera/spark-kafka-writer#3]
Hi,

NOT AN ISSUE MORE OF A QUESTION: 

How are you handling messages that are in buffer ready to be written out but have not been flushed out and the server is terminated/crashed?  Are you ensuring that messages are written out before system is terminated?

**Comment by harishreedharan** [comment]
Actually we don't buffer any data. We send the data using the synchronous API. Once that returns, the batch is complete. So if the write fails or the app/node crashes before the writes are completed, then the whole batch would get retried by Spark anyway and the write would go through when that happens.

**Comment by dimanyudev** [comment]
Thanks for the reply.  One more question, how is the batch size configured.  I will try and come back if I have any questions.

**Comment by harishreedharan** [comment]
The batch size is basically configured indirectly via spark. All events in a batch interval are passed down from Spark Streaming. You don't need to configure batch sizes yourself.

**Comment by dimanyudev** [comment]
Thanks, i will close the non-issue.
